services:
  sonicai-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sonicai-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    networks:
      - sonicai_net

networks:
  sonicai_net:
    external: true
